language: python

os:
  - linux

python:
  - "3.7"

install:
  # install all the project dependencies
  - poetry install

  # install all the plugins to be able to run
  # integrational tests
  - python ./tools.py bootstrap

script:
  - PYTHONPATH=. py.test
