packages:
  path: packages
  repositories:
  - https://pastebin.com/raw/VkZ5DteD
plugins:
  command-alias:
  - /a /activate-thought
  - /cc /create-child
  - /cp /create-parent
  - /cr /create-reference
  disabled: []

  # local storage configuration
  local-storage:
    # path to save all your data
    root_path: ~/Brains/


  # folders plugin configuration
  folder@components:
    # template to calculate the path where your files will be saved
    path_template: Files/{category}/{tags}/{title}

    # hierarchy of paths
    tags_hierarchy:
      # "Recepie" is a category
      # - Recipe:
      #     - Starter:
      #     - Soup
      #  - Dessert:
      #     - Cake
      #     - Pie
      # "Idea" is a category
      # - Idea:
      #     - Goal of life
      #     - House
      #     - Work
