packages:
  path: packages
  repositories:
    - https://pastebin.com/raw/RHwj6jGz
stores:
  local:
    path: brains
plugins:
  folder@components:
    template: "Files/{year}/{title}"
  command-alias:
    - /a /activate-thought
    - /cc /create-child
    - /cp /create-parent
    - /cr /create-reference
  