# packages configuration section
packages:
  # path to plugins folder
  path: packages
  
  # list of repositories to get
  # plugins information from
  repositories:
    - https://pastebin.com/raw/qqCwanS7
